### ISSUE TITLE
bugfix "messages w/o received header"

### ISSUE THREAD

**Issue by mrdsam** [NETWAYS/check_email#4]
Hi, 
the script crashes if there are mails in the mailbox without a 'Received'-Header. These are mails injected directly into my mailbox by my provider. 

Added 2 lines of code to catch this, maybe you want to adopt https://github.com/mrdsam/check_email/blob/master/check_email line 150

**Comment by Al2Klimov** [comment]
Maybe _you_ want to open a PR?

**Comment by mrdsam** [comment]
I've also done changes you may not want to adopt, but yes, I'll do.
I'd also want to point you to my solution at line 118: Using "splitlines" is a bug because a "Received" line can span multiple lines.
